services:
    eureka:
        build: ./Gateway/eureka
        container_name: eureka
        networks:
            mynet1:
                ipv4_address: 172.28.0.2
        ports:
            - 8761:8761

    # apirest:
    #     build: ./Gateway/apirest
    #     container_name: apirest
    #     networks:
    #         mynet1:
    #             ipv4_address: 172.28.0.3
    #     ports:
    #         - 8888:8888
    #     depends_on:
    #         - eureka

    servicios:
        build: ./Microservicios/servicio
        container_name: servicios
        networks:
            mynet1:
                ipv4_address: 172.28.0.4
        # ports:
        #     - 9080:9080
        environment:
            - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
        depends_on:
            - eureka
            # - apirest

    usuarios:
        build: ./Microservicios/usuarios
        container_name: usuarios
        networks:
            mynet1:
                ipv4_address: 172.28.0.5
        # ports:
        #     - 9090:9090
        environment:
            - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
        depends_on:
            - eureka
            # - apirest
    facturacion:
        build: ./Microservicios/facturacion
        container_name: facturacion
        networks:
            mynet1:
                ipv4_address: 172.28.0.6
        # ports:
        #     - 9070:9070
        environment:
            - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
        depends_on:
            - eureka
            # - apirest
networks:
    default:
        name: mynet
        driver: bridge
    mynet1:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/24
                  gateway: 172.28.0.1